spring:
  motan:
    annotation:
      package: cc.ostay.service
    protocol:
      name: motan
      is-default: true
      max-server-connection: 80000
      max-content-length: 1048576
      max-worker-thread: 800
      min-worker-thread: 20
    registry:
      reg-protocol: zookeeper
      address: 172.168.6.18:2181
    server:
      registry: registry
      export: motan:1010
      access-log: false
      share-channel: true
      application: demo
      request-timeout: 15000
      version: 1.0

logging:
  level:
    root: debug